// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChvtAd7dUZ0NJdHV8jfyTm7A4p56xqSb0',
    appId: '1:280220032658:web:057490c491571bc204904b',
    messagingSenderId: '280220032658',
    projectId: 'my-github-flutter-blog',
    authDomain: 'my-github-flutter-blog.firebaseapp.com',
    storageBucket: 'my-github-flutter-blog.firebasestorage.app',
    measurementId: 'G-XBR66EY9TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEV8Ducr6e2X4__NFxddJudR8XU6EdARU',
    appId: '1:280220032658:android:f26d9580afcf9d8704904b',
    messagingSenderId: '280220032658',
    projectId: 'my-github-flutter-blog',
    storageBucket: 'my-github-flutter-blog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRP1CqfLqz3ZjuZFukI018JACD3Z-eE0',
    appId: '1:280220032658:ios:cd08be1e5daab58f04904b',
    messagingSenderId: '280220032658',
    projectId: 'my-github-flutter-blog',
    storageBucket: 'my-github-flutter-blog.firebasestorage.app',
    iosBundleId: 'com.example.githubBlog',
  );
}
